### ISSUE TITLE
MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by zachsa** [jspm/generator#123]
MODULE_NOT_FOUND error while generating import map

Please let me know if this is enough information, or what else I can provide. I think this is related to node std lib

```
file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1594
                throw new JspmError(`Module not found: ${resolvedUrl}${importedFrom(parentUrl)}`, 'MODULE_NOT_FOUND');
                      ^

JspmError: Module not found: https://ga.jspm.io/npm:object-inspect@1.12.0/util.inspect.js imported from https://ga.jspm.io/npm:object-inspect@1.12.0/index.js
    at Resolver.analyze (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1594:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TraceMap.traceUrl (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1962:71)
    at async TraceMap.trace (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1931:13)
    at async file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1992:30
    at async Promise.all (index 0)
    at async TraceMap.traceUrl (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1987:9)
    at async TraceMap.trace (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1942:13)
    at async file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator.js:1992:30
    at async Promise.all (index 2) {
  jspmError: true,
  code: 'MODULE_NOT_FOUND'
}
```

This occurs with the following import:

```
import { ApolloServer } from 'apollo-server-koa'
```

**Comment by zachsa** [comment]
My current workaround for this is to pass `ignore: ['apollo-server-koa']` to the generator
