### ISSUE TITLE
jspm incorrectly considers a local dependency to be commonjs

### ISSUE THREAD

**Issue by nex3** [jspm/generator#259]
```shellsession
$ mkdir pkg
$ npm i @jspm/generator
$ mkdir subpkg
$ echo '{"name": "subpkg", "version": "0.0.0", "main": "index.js"}' > subpkg/package.json
$ echo 'console.log("hello!")' > subpkg/index.js
$ cat > generate.mjs
import { Generator } from '@jspm/generator';

const generator = new Generator({
  mapUrl: import.meta.url,
  defaultProvider: 'nodemodules',
  env: ['production', 'browser', 'module'],
});

await generator.install('./subpkg');
$ node generate.mjs
file:///tmp/pkg/node_modules/@jspm/generator/dist/generator-0681485c.js:2565
            throw new JspmError(`Unable to trace ${resolved}, as it is a CommonJS module. Either enable CommonJS tracing explicitly by setting "GeneratorOptions.commonJS" to true, or use a provider that performs ESM transpiling like jspm.io via defaultProvider: 'jspm.io'.`);
                  ^

JspmError: Unable to trace file:///tmp/pkg/subpkg/index.js, as it is a CommonJS module. Either enable CommonJS tracing explicitly by setting "GeneratorOptions.commonJS" to true, or use a provider that performs ESM transpiling like jspm.io via defaultProvider: 'jspm.io'.
    at TraceMap.visit (file:///tmp/pkg/node_modules/@jspm/generator/dist/generator-0681485c.js:2565:19)                                                      
    at async Generator.install (file:///tmp/pkg/node_modules/@jspm/generator/dist/generator-0681485c.js:3854:13)                                                      
    at async file:///tmp/pkg/generate.mjs:11:1 {
  jspmError: true,
  code: undefined
}

Node.js v19.7.0
```

It looks like jspm is considering my `subpkg/index.js` file to be a CommonJS file, despite not using any CommonJS features and being entirely possible to import via ESM. Even if I explicitly declare it as a non-CommonJS file using package.json conditional exports, jspm still throws this error. I can work around it by passing `commonJS: true`, but as a library author I'd like to avoid requiring my users to do that.

Note that while this is a toy example, my real use-case is more serious: I'm trying to distribute a library that will seamlessly support both CJS and ESM users with the same codebase. To do so, I use side effects when the library is loaded via ESM to pass out its exports without violating CJS syntax.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/generator/pull/261.
