### ISSUE TITLE
JspmError: No provider named "jspm" has been defined.

### ISSUE THREAD

**Issue by zachsa** [jspm/generator#274]
Updating from `1.0.4` to `1.1.1` results in the following error:

```
JspmError: No provider named "jspm" has been defined.
    at getProvider (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator-217ec034.js:1185:11)
    at Resolver.resolveLatestTarget (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator-217ec034.js:1447:37)
    at Installer.installTarget (file:///home/zach/code/saeon/repositories/somisana/web/node_modules/@jspm/generator/dist/generator-217ec034.js:2402:47) {
  jspmError: true,
  code: undefined
}
```

From this code:

```js
import { Generator } from '@jspm/generator'
import { pathToFileURL } from 'url'

const NODE_ENV = process.env.NODE_ENV || 'development'
const TARGET = process.env.TARGET

const generator = new Generator({
  mapUrl: pathToFileURL(TARGET),
  env: ['browser', NODE_ENV, 'module'],
  defaultProvider: 'jspm',
  ignore: [],
})
```

**Comment by Bubblyworld** [comment]
Hey, so the `jspm` provider was renamed `jspm.io` in `1.1.0` - you can either use that or just leave out `defaultProvider` entirely (it defaults to `jspm.io` if nothing is provided).

**Comment by zachsa** [comment]
Ah thanks. That works

**Comment by Bubblyworld** [comment]
In hindsight shouldn't have been a breaking change, I'm going to alias `jspm` to `jspm.io`, sorry about that!
