### ISSUE TITLE
RangeError in resolver

### ISSUE THREAD

**Issue by jollytoad** [jspm/generator#6]
Test case:

```typescript
import { Generator } from '#dev';

const generator = new Generator();

await generator.install({ target: 'monaco-editor@0.23.0', subpath: './esm/vs/editor/editor.api' });
```

output:

```
➜  generator git:(main) ✗ npm test

> @jspm/generator@1.0.0-beta.1 test
> node test/test.js

............> /*---------------------------------------------------------------------------------------------
file:///Users/mgibson/github/generator/lib/install/resolver.js:339
                    console.log('  ' + ' '.repeat(col - 1) + '^');
                                           ^

RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at Resolver.analyze (file:///Users/mgibson/github/generator/lib/install/resolver.js:339:44)
    at async TraceMap.traceUrl (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:240:64)
    at async TraceMap.trace (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:144:13)
    at async file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:254:30
    at async Promise.all (index 84)
    at async TraceMap.traceUrl (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:253:9)
    at async TraceMap.trace (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:206:17)
    at async Generator.install (file:///Users/mgibson/github/generator/lib/generator.js:32:13)
    at async file:///Users/mgibson/github/generator/test/errors/range-error.test.js:5:1
...
```

**Comment by jollytoad** [comment]
Root cause:

https://github.com/jspm/generator/blob/06c11bb27a78dd92b2710e6fcc6875172433ad4c/src/install/resolver.ts#L354

indexof may return -1

I'd suggest a split to get the top line:

```
          const [topline] = e.message.split('\n', 1);
          const pos = topline.slice(14);
```

**Comment by jollytoad** [comment]
the test case now gives me...

```
➜  generator git:(main) ✗ npm test     

> @jspm/generator@1.0.0-beta.1 test
> node test/test.js

............> /*---------------------------------------------------------------------------------------------
  ^
   *  Copyright (c) Microsoft Corporation. All rights reserved.
file:///Users/mgibson/github/generator/lib/install/resolver.js:343
                    throw new JspmError(`Error parsing ${resolvedUrl}:${pos}`);
                          ^

JspmError: Error parsing https://ga.jspm.io/npm:monaco-editor@0.23.0/esm/vs/base/browser/ui/mouseCursor/mouseCursor.css:1:1
    at Resolver.analyze (file:///Users/mgibson/github/generator/lib/install/resolver.js:343:27)
    at async TraceMap.traceUrl (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:240:64)
    at async TraceMap.trace (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:144:13)
    at async file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:254:30
    at async Promise.all (index 84)
    at async TraceMap.traceUrl (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:253:9)
    at async TraceMap.trace (file:///Users/mgibson/github/generator/lib/tracemap/tracemap.js:206:17)
    at async Generator.install (file:///Users/mgibson/github/generator/lib/generator.js:32:13)
    at async file:///Users/mgibson/github/generator/test/errors/range-error.test.js:5:1 {
  jspmError: true,
  code: undefined
}
...
```

which is a lot more useful 😄

**Comment by guybedford** [comment]
Thanks for the suggestion, added in https://github.com/jspm/generator/commit/991da4a3090c608468c937287684e02a2df3ea2e.
